# Generated by Django 2.2.10 on 2019-11-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spec_cpu', models.CharField(max_length=100)),
                ('spec_ram', models.CharField(max_length=100)),
                ('spec_ssd', models.CharField(max_length=100)),
                ('spec_screen', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=255)),
                ('warranty', models.CharField(default='Garantie 1 mois', max_length=50)),
            ],
        ),
    ]
