# Generated by Django 2.2.10 on 2019-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
