"""depo URL Configuration

generated by django-admin startproject
"""
from django.contrib import admin
from django.urls import path
# from django.urls import include
from .views import home
# from .views import products_page, cart_page  # TODO
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home, name='home'),
    # path('home/', home, name='home2'),  # alias - not sure if needed
    # path('products/', products_page, name='products'),  # TODO
    # path('cart/', cart_page, name='cart'),  # TODO
    path('admin/', admin.site.urls),
]

# serve media files in dev mode only
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # not needed?
